from app.models import User, Board, Page

INITIAL_CANVAS_ELEMENTS = [
  {
    "id": "hl-title",
    "type": "highlighter",
    "points": [{"x": 50, "y": 55, "pressure": 0.8}, {"x": 340, "y": 55, "pressure": 0.9}],
    "color": "#fef08a",
    "size": 32,
    "opacity": 0.5,
    "x": 50,
    "y": 40,
    "width": 290,
    "height": 32,
    "zIndex": 1
  },
  {
    "id": "text-title",
    "type": "text",
    "text": "JavaScript Variables",
    "fontFamily": "handwriting",
    "fontSize": 40,
    "color": "#0f172a",
    "bold": True,
    "x": 55,
    "y": 35,
    "width": 320,
    "height": 48,
    "zIndex": 2
  },
  {
    "id": "bullet-1-dot",
    "type": "circle",
    "x": 42,
    "y": 110,
    "width": 8,
    "height": 8,
    "strokeColor": "#ef4444",
    "fillColor": "#ef4444",
    "strokeWidth": 1,
    "strokeStyle": "solid",
    "zIndex": 3
  },
  {
    "id": "bullet-1-text",
    "type": "text",
    "text": "A variable is a named reference\nto a value stored in memory.",
    "fontFamily": "handwriting",
    "fontSize": 22,
    "color": "#1e293b",
    "x": 60,
    "y": 100,
    "width": 330,
    "height": 60,
    "zIndex": 3
  },
  {
    "id": "bullet-2-dot",
    "type": "circle",
    "x": 42,
    "y": 185,
    "width": 8,
    "height": 8,
    "strokeColor": "#ef4444",
    "fillColor": "#ef4444",
    "strokeWidth": 1,
    "strokeStyle": "solid",
    "zIndex": 3
  },
  {
    "id": "bullet-2-text",
    "type": "text",
    "text": "We use variables to store data\nwhich can be used and changed\nlater in the program.",
    "fontFamily": "handwriting",
    "fontSize": 21,
    "color": "#1e293b",
    "x": 60,
    "y": 175,
    "width": 330,
    "height": 75,
    "zIndex": 3
  },
  {
    "id": "hl-syntax",
    "type": "highlighter",
    "points": [{"x": 70, "y": 285, "pressure": 0.8}, {"x": 145, "y": 285, "pressure": 0.8}],
    "color": "#fbcfe8",
    "size": 26,
    "opacity": 0.6,
    "x": 70,
    "y": 275,
    "width": 75,
    "height": 26,
    "zIndex": 2
  },
  {
    "id": "text-syntax-label",
    "type": "text",
    "text": "Syntax",
    "fontFamily": "handwriting",
    "fontSize": 24,
    "color": "#0f172a",
    "bold": True,
    "x": 74,
    "y": 270,
    "width": 70,
    "height": 30,
    "zIndex": 4
  },
  {
    "id": "syntax-box-frame",
    "type": "rounded-rectangle",
    "x": 55,
    "y": 265,
    "width": 280,
    "height": 90,
    "strokeColor": "#f43f5e",
    "fillColor": "#fff1f2",
    "strokeWidth": 2,
    "strokeStyle": "dashed",
    "cornerRadius": 12,
    "zIndex": 2
  },
  {
    "id": "text-syntax-code",
    "type": "text",
    "text": "let  variableName  =  value;",
    "fontFamily": "handwriting",
    "fontSize": 22,
    "color": "#0f172a",
    "bold": True,
    "x": 75,
    "y": 310,
    "width": 250,
    "height": 32,
    "zIndex": 5
  },
  {
    "id": "main-code-block",
    "type": "code",
    "x": 400,
    "y": 35,
    "width": 380,
    "height": 330,
    "language": "javascript",
    "theme": "dark",
    "title": "// variable declaration",
    "code": '// variable declaration\nlet name = "Nagarjun";        // string\nlet age = 25;                 // number\nlet isStudent = true;         // boolean\nlet hobbies = ["Coding", "Gym"]; // array\nlet user = {\n  name: "Nagarjun",           // object\n  age: 25\n};',
    "zIndex": 10
  },
  {
    "id": "hl-mem",
    "type": "highlighter",
    "points": [{"x": 55, "y": 395, "pressure": 0.8}, {"x": 305, "y": 395, "pressure": 0.8}],
    "color": "#bbf7d0",
    "size": 28,
    "opacity": 0.5,
    "x": 55,
    "y": 385,
    "width": 250,
    "height": 28,
    "zIndex": 2
  },
  {
    "id": "text-mem-title",
    "type": "text",
    "text": "Memory Representation",
    "fontFamily": "handwriting",
    "fontSize": 26,
    "color": "#0f172a",
    "bold": True,
    "x": 60,
    "y": 380,
    "width": 250,
    "height": 34,
    "zIndex": 4
  },
  {
    "id": "box-name-key",
    "type": "rounded-rectangle",
    "x": 70,
    "y": 430,
    "width": 100,
    "height": 40,
    "strokeColor": "#ca8a04",
    "fillColor": "#fef9c3",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-name-key",
    "type": "text",
    "text": "name",
    "fontFamily": "sans",
    "fontSize": 16,
    "bold": True,
    "color": "#1e293b",
    "align": "center",
    "x": 70,
    "y": 440,
    "width": 100,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "arrow-name",
    "type": "arrow",
    "x": 175,
    "y": 450,
    "width": 60,
    "height": 0,
    "strokeColor": "#0f172a",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "box-name-val",
    "type": "rounded-rectangle",
    "x": 240,
    "y": 430,
    "width": 110,
    "height": 40,
    "strokeColor": "#e11d48",
    "fillColor": "#ffe4e6",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-name-val",
    "type": "text",
    "text": '"Nagarjun"',
    "fontFamily": "mono",
    "fontSize": 15,
    "bold": True,
    "color": "#be123c",
    "align": "center",
    "x": 240,
    "y": 440,
    "width": 110,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "box-age-key",
    "type": "rounded-rectangle",
    "x": 70,
    "y": 485,
    "width": 100,
    "height": 40,
    "strokeColor": "#ca8a04",
    "fillColor": "#fef9c3",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-age-key",
    "type": "text",
    "text": "age",
    "fontFamily": "sans",
    "fontSize": 16,
    "bold": True,
    "color": "#1e293b",
    "align": "center",
    "x": 70,
    "y": 495,
    "width": 100,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "arrow-age",
    "type": "arrow",
    "x": 175,
    "y": 505,
    "width": 60,
    "height": 0,
    "strokeColor": "#0f172a",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "box-age-val",
    "type": "rounded-rectangle",
    "x": 240,
    "y": 485,
    "width": 110,
    "height": 40,
    "strokeColor": "#2563eb",
    "fillColor": "#dbeafe",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-age-val",
    "type": "text",
    "text": "25",
    "fontFamily": "mono",
    "fontSize": 16,
    "bold": True,
    "color": "#1d4ed8",
    "align": "center",
    "x": 240,
    "y": 495,
    "width": 110,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "box-stu-key",
    "type": "rounded-rectangle",
    "x": 70,
    "y": 540,
    "width": 100,
    "height": 40,
    "strokeColor": "#ca8a04",
    "fillColor": "#fef9c3",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-stu-key",
    "type": "text",
    "text": "isStudent",
    "fontFamily": "sans",
    "fontSize": 15,
    "bold": True,
    "color": "#1e293b",
    "align": "center",
    "x": 70,
    "y": 550,
    "width": 100,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "arrow-stu",
    "type": "arrow",
    "x": 175,
    "y": 560,
    "width": 60,
    "height": 0,
    "strokeColor": "#0f172a",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "box-stu-val",
    "type": "rounded-rectangle",
    "x": 240,
    "y": 540,
    "width": 110,
    "height": 40,
    "strokeColor": "#16a34a",
    "fillColor": "#dcfce7",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-stu-val",
    "type": "text",
    "text": "true",
    "fontFamily": "mono",
    "fontSize": 16,
    "bold": True,
    "color": "#15803d",
    "align": "center",
    "x": 240,
    "y": 550,
    "width": 110,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "text-mem-caption",
    "type": "text",
    "text": "Variables store values in memory.\nEach variable has a name and a value.",
    "fontFamily": "handwriting",
    "fontSize": 20,
    "color": "#2563eb",
    "x": 65,
    "y": 600,
    "width": 320,
    "height": 50,
    "zIndex": 4
  },
  {
    "id": "divider-col-1",
    "type": "line",
    "x": 395,
    "y": 395,
    "width": 0,
    "height": 260,
    "strokeColor": "#cbd5e1",
    "strokeWidth": 2,
    "strokeStyle": "dashed",
    "zIndex": 2
  },
  {
    "id": "hl-rules",
    "type": "highlighter",
    "points": [{"x": 420, "y": 395, "pressure": 0.8}, {"x": 620, "y": 395, "pressure": 0.8}],
    "color": "#e9d5ff",
    "size": 28,
    "opacity": 0.6,
    "x": 420,
    "y": 385,
    "width": 200,
    "height": 28,
    "zIndex": 2
  },
  {
    "id": "text-rules-title",
    "type": "text",
    "text": "Rules for Variables",
    "fontFamily": "handwriting",
    "fontSize": 26,
    "color": "#0f172a",
    "bold": True,
    "x": 425,
    "y": 380,
    "width": 200,
    "height": 34,
    "zIndex": 4
  },
  {
    "id": "badge-rule-1",
    "type": "circle",
    "x": 420,
    "y": 430,
    "width": 24,
    "height": 24,
    "strokeColor": "#ec4899",
    "fillColor": "#fdf2f8",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "text-badge-1",
    "type": "text",
    "text": "1",
    "fontFamily": "sans",
    "fontSize": 14,
    "bold": True,
    "color": "#db2777",
    "align": "center",
    "x": 420,
    "y": 432,
    "width": 24,
    "height": 24,
    "zIndex": 5
  },
  {
    "id": "text-rule-1-desc",
    "type": "text",
    "text": "Can start with a letter, _ or $",
    "fontFamily": "handwriting",
    "fontSize": 21,
    "color": "#1e293b",
    "x": 455,
    "y": 428,
    "width": 280,
    "height": 28,
    "zIndex": 4
  },
  {
    "id": "badge-rule-2",
    "type": "circle",
    "x": 420,
    "y": 475,
    "width": 24,
    "height": 24,
    "strokeColor": "#eab308",
    "fillColor": "#fefce8",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "text-badge-2",
    "type": "text",
    "text": "2",
    "fontFamily": "sans",
    "fontSize": 14,
    "bold": True,
    "color": "#ca8a04",
    "align": "center",
    "x": 420,
    "y": 477,
    "width": 24,
    "height": 24,
    "zIndex": 5
  },
  {
    "id": "text-rule-2-desc",
    "type": "text",
    "text": "Cannot start with a number",
    "fontFamily": "handwriting",
    "fontSize": 21,
    "color": "#1e293b",
    "x": 455,
    "y": 473,
    "width": 280,
    "height": 28,
    "zIndex": 4
  },
  {
    "id": "badge-rule-3",
    "type": "circle",
    "x": 420,
    "y": 520,
    "width": 24,
    "height": 24,
    "strokeColor": "#3b82f6",
    "fillColor": "#eff6ff",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "text-badge-3",
    "type": "text",
    "text": "3",
    "fontFamily": "sans",
    "fontSize": 14,
    "bold": True,
    "color": "#2563eb",
    "align": "center",
    "x": 420,
    "y": 522,
    "width": 24,
    "height": 24,
    "zIndex": 5
  },
  {
    "id": "text-rule-3-desc",
    "type": "text",
    "text": "Can contain letters, numbers, _ or $",
    "fontFamily": "handwriting",
    "fontSize": 21,
    "color": "#1e293b",
    "x": 455,
    "y": 518,
    "width": 300,
    "height": 28,
    "zIndex": 4
  },
  {
    "id": "badge-rule-4",
    "type": "circle",
    "x": 420,
    "y": 565,
    "width": 24,
    "height": 24,
    "strokeColor": "#22c55e",
    "fillColor": "#f0fdf4",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "text-badge-4",
    "type": "text",
    "text": "4",
    "fontFamily": "sans",
    "fontSize": 14,
    "bold": True,
    "color": "#16a34a",
    "align": "center",
    "x": 420,
    "y": 567,
    "width": 24,
    "height": 24,
    "zIndex": 5
  },
  {
    "id": "text-rule-4-desc",
    "type": "text",
    "text": "Cannot be a reserved keyword",
    "fontFamily": "handwriting",
    "fontSize": 21,
    "color": "#1e293b",
    "x": 455,
    "y": 563,
    "width": 280,
    "height": 28,
    "zIndex": 4
  },
  {
    "id": "badge-rule-5",
    "type": "circle",
    "x": 420,
    "y": 610,
    "width": 24,
    "height": 24,
    "strokeColor": "#a855f7",
    "fillColor": "#faf5ff",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "text-badge-5",
    "type": "text",
    "text": "5",
    "fontFamily": "sans",
    "fontSize": 14,
    "bold": True,
    "color": "#9333ea",
    "align": "center",
    "x": 420,
    "y": 612,
    "width": 24,
    "height": 24,
    "zIndex": 5
  },
  {
    "id": "text-rule-5-desc",
    "type": "text",
    "text": "Case sensitive\n(name and Name are different)",
    "fontFamily": "handwriting",
    "fontSize": 20,
    "color": "#1e293b",
    "x": 455,
    "y": 608,
    "width": 280,
    "height": 48,
    "zIndex": 4
  },
  {
    "id": "hl-datatypes",
    "type": "highlighter",
    "points": [{"x": 810, "y": 345, "pressure": 0.8}, {"x": 1070, "y": 345, "pressure": 0.8}],
    "color": "#fbcfe8",
    "size": 28,
    "opacity": 0.6,
    "x": 810,
    "y": 335,
    "width": 260,
    "height": 28,
    "zIndex": 2
  },
  {
    "id": "text-datatypes-title",
    "type": "text",
    "text": "Data Types in JavaScript",
    "fontFamily": "handwriting",
    "fontSize": 26,
    "color": "#0f172a",
    "bold": True,
    "x": 815,
    "y": 330,
    "width": 260,
    "height": 34,
    "zIndex": 4
  },
  {
    "id": "box-dt-root",
    "type": "rounded-rectangle",
    "x": 865,
    "y": 385,
    "width": 120,
    "height": 38,
    "strokeColor": "#16a34a",
    "fillColor": "#dcfce7",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-dt-root",
    "type": "text",
    "text": "Data Types",
    "fontFamily": "sans",
    "fontSize": 16,
    "bold": True,
    "color": "#15803d",
    "align": "center",
    "x": 865,
    "y": 393,
    "width": 120,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "arrow-branch-left",
    "type": "arrow",
    "x": 890,
    "y": 425,
    "width": -40,
    "height": 30,
    "strokeColor": "#0f172a",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "arrow-branch-right",
    "type": "arrow",
    "x": 960,
    "y": 425,
    "width": 40,
    "height": 30,
    "strokeColor": "#0f172a",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "zIndex": 4
  },
  {
    "id": "box-dt-primitive",
    "type": "rounded-rectangle",
    "x": 785,
    "y": 465,
    "width": 110,
    "height": 38,
    "strokeColor": "#2563eb",
    "fillColor": "#eff6ff",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-dt-primitive",
    "type": "text",
    "text": "Primitive",
    "fontFamily": "sans",
    "fontSize": 16,
    "bold": True,
    "color": "#1d4ed8",
    "align": "center",
    "x": 785,
    "y": 473,
    "width": 110,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "text-primitive-list",
    "type": "text",
    "text": "•  String\n•  Number\n•  Boolean\n•  Undefined\n•  Null\n•  Symbol\n•  BigInt",
    "fontFamily": "handwriting",
    "fontSize": 20,
    "color": "#1e293b",
    "x": 795,
    "y": 515,
    "width": 120,
    "height": 160,
    "zIndex": 4
  },
  {
    "id": "box-dt-non-primitive",
    "type": "rounded-rectangle",
    "x": 935,
    "y": 465,
    "width": 130,
    "height": 38,
    "strokeColor": "#7c3aed",
    "fillColor": "#f5f3ff",
    "strokeWidth": 2,
    "strokeStyle": "solid",
    "cornerRadius": 8,
    "zIndex": 3
  },
  {
    "id": "text-dt-non-primitive",
    "type": "text",
    "text": "Non-Primitive",
    "fontFamily": "sans",
    "fontSize": 16,
    "bold": True,
    "color": "#6d28d9",
    "align": "center",
    "x": 935,
    "y": 473,
    "width": 130,
    "height": 25,
    "zIndex": 4
  },
  {
    "id": "text-non-primitive-list",
    "type": "text",
    "text": "•  Object\n•  Array\n•  Function",
    "fontFamily": "handwriting",
    "fontSize": 20,
    "color": "#1e293b",
    "x": 945,
    "y": 515,
    "width": 120,
    "height": 90,
    "zIndex": 4
  }
]

def seed_database_if_empty(db_session):
    # Check if demo user already exists
    user = db_session.query(User).filter_by(email="nagarjun@youtube.creator").first()
    if not user:
        user = User(
            id="user-demo",
            name="Nagarjun",
            email="nagarjun@youtube.creator"
        )
        user.set_password("password123")
        db_session.add(user)
        db_session.flush()

    # Check if boards exist
    board_count = db_session.query(Board).filter_by(user_id=user.id).count()
    if board_count == 0:
        # Create JavaScript Complete Board
        js_board = Board(
            id="board-js",
            user_id=user.id,
            name="JavaScript Complete",
            description="Complete JavaScript tutorial series for YouTube",
            is_favorite=True
        )
        db_session.add(js_board)
        db_session.flush()

        # Seed the 9 lesson pages
        lessons = [
            ("page-js-01", "01. Variables and Data Types", INITIAL_CANVAS_ELEMENTS),
            ("page-js-02", "02. Operators", []),
            ("page-js-03", "03. Conditions", []),
            ("page-js-04", "04. Loops", []),
            ("page-js-05", "05. Functions", []),
            ("page-js-06", "06. Arrays", []),
            ("page-js-07", "07. Objects", []),
            ("page-js-08", "08. DOM", []),
            ("page-js-09", "09. Events", []),
        ]

        for i, (pid, title, elements) in enumerate(lessons):
            page = Page(
                id=pid,
                board_id=js_board.id,
                name=title,
                position=i,
                canvas_state={"elements": elements, "viewport": {"x": 0, "y": 0, "zoom": 1}},
                background_config={"style": "white"}
            )
            db_session.add(page)

        # Other boards
        other_boards = [
            ("board-python", "Python Series", "Python 3 Masterclass", [("01. Python Basics & Syntax", "graph")]),
            ("board-dsa", "DSA", "Data Structures and Algorithms", [("01. Arrays and Two Pointers", "grid")]),
            ("board-webdev", "Web Development", "Full Stack Development", [("01. HTTP & Client Server", "ruled")]),
            ("board-trading", "Trading Notes", "Technical Analysis", [("01. Candlestick Patterns", "chalkboard")]),
        ]

        for b_id, b_name, b_desc, b_pages in other_boards:
            b = Board(id=b_id, user_id=user.id, name=b_name, description=b_desc)
            db_session.add(b)
            db_session.flush()
            for p_idx, (p_title, bg_style) in enumerate(b_pages):
                p = Page(
                    id=f"page-{b_id}-{p_idx}",
                    board_id=b.id,
                    name=p_title,
                    position=p_idx,
                    canvas_state={"elements": [], "viewport": {"x": 0, "y": 0, "zoom": 1}},
                    background_config={"style": bg_style}
                )
                db_session.add(p)

        db_session.commit()
        print("Database pre-seeded with YouTube lesson curriculum successfully.")
